### ISSUE TITLE
Data Feeds similar to GTFS

### ISSUE THREAD

**Issue by HiGregory** [openmobilityfoundation/curb-data-specification#109]
Apparently, Philly is using CDS and would love to get access to their feeds or example. 

Is there a way for us to document Pilots of CDS API? See reference: https://twitter.com/Wheelmrk/status/1577018891255308288

**Comment by schnuerle** [comment]
FYI more info on Philly's CDS pilot:

FAQ (PDF)
https://www.phila.gov/media/20221003122355/Smart-Loading-Zones-FAQ.pdf

Map
https://www.phila.gov/media/20220930084427/Smart-Loading-Zones-map.png

Webpage
https://www.phila.gov/programs/smartcityphl/smart-loading-zones/

Article
https://www.smartcitiesdive.com/news/philadelphia-loading-zones-smartcityphl-curb-data-specification-sidewalk-labs-pebble/634269/

It looks like Pebble has incorporated the CDS Curbs data into their fleet driver app.
