### ISSUE TITLE
Update documentation for Curb Event to reference event_location

### ISSUE THREAD

**Issue by michael-danko-passport** [openmobilityfoundation/curb-data-specification#110]
### Is your feature request related to a problem? Please describe.

Currently the `event_location` field is defined as a `GeoJSON` type but we have not defined what those values should look like. In the Jan 17th CDS WGSC meeting, it was discussed that we have defined this within the CDS spec [here](https://github.com/openmobilityfoundation/curb-data-specification/blob/main/general-information.md#geographic-telemetry-data) but have not linked it to this particular API endpoint.

### Describe the solution you'd like

Update the documentation to define the type of values expected to be within the Event. 

### Is this a breaking change

No, this can be a fix version update,

### Impacted Spec
 * `Events`

**Comment by schnuerle** [comment]
We will be talking about this at next week's [Working Group meeting](https://github.com/openmobilityfoundation/curb-data-specification/wiki/Web-Conference-2023.06.27-Curb#agenda) for inclusion in a forthcoming CDS 1.0.1 patch release, so please attend if you can.

**Comment by schnuerle** [comment]
I think the `event_location` field in [Curb Event](https://github.com/openmobilityfoundation/curb-data-specification/tree/main/events#curb-event) just needs to link to the GeoJSON description. We can handle this in the upcoming 1.0.1 patch release.

**Comment by schnuerle** [comment]
If anyone wants to do a PR for this, that would be welcome and you and your org will be recognized in the acknowledgements for 1.0.1. Otherwise the OMF staff will make a PR soon.

**Comment by schnuerle** [comment]
Thank you for the PR Mitch!
