### ISSUE TITLE
Zone and space compliance

### ISSUE THREAD

**Issue by MirandaBradshawPassport** [openmobilityfoundation/curb-data-specification#127]
### Is your feature request related to a problem? Please describe.

Clients have expressed concerns that drawing zones and spaces on a map will be time consuming. Is dropping a single point (one lat/long) on the map to represent a space or zone considered CDS compliant? Are poly-lines to represent zones or spaces compliant?

### Describe the solution you'd like

It would save time for large operations with hundreds of zones and thousands of spaces if they didn't have to draw polygons for every zone and every space.

### Is this a breaking change

A breaking change would require consumers or implementors of an API to modify their code for it to continue to function (ex: renaming of a required field or the change in data type of an existing field). A non-breaking change would allow existing code to continue to function (ex: addition of an optional field or the creation of a new optional endpoint). 

 * Yes, breaking
 * No, not breaking
 * I'm not sure <<this one

### Impacted Spec

For which spec is this feature being requested?

 * `Curbs` <<this one
 * `Events`
 * `Metrics`

### Describe alternatives you've considered

If a single point or poly-line is not compliant, then can we make that really explicit in the documentation?

**Comment by MirandaBradshawPassport** [comment]
I don't know if this is the right place to ask these questions, so I'm happy to receive feedback on that.

**Comment by mplsmitch** [comment]
This seems closely related to #119, maybe these two issues could be consolidated.

**Comment by schnuerle** [comment]
Yes currently it has to be a polygon. 
 
I'm going to close this issue, but copy and paste your comments into the discussion at #119 like Mitch mentioned
