### ISSUE TITLE
Clarify `street name` field description

### ISSUE THREAD

**Issue by MirandaBradshawPassport** [openmobilityfoundation/curb-data-specification#128]
### Is your feature request related to a problem? Please describe.

It's unclear in the documentation whether the street_name field is allowed to contain the actual street address of the zone. Ex: Is "438 N Center St" compliant? Or is street_name meant to literally contain just the street name (e.g. "Center St")

### Describe the solution you'd like

Either scenario is fine, the documentation just doesn't seem explicit.

### Is this a breaking change

A breaking change would require consumers or implementors of an API to modify their code for it to continue to function (ex: renaming of a required field or the change in data type of an existing field). A non-breaking change would allow existing code to continue to function (ex: addition of an optional field or the creation of a new optional endpoint). 

 * Yes, breaking
 * No, not breaking
 * I'm not sure<<this one

### Impacted Spec

For which spec is this feature being requested?

 * `Curbs`<<this one
 * `Events`
 * `Metrics`

**Comment by MirandaBradshawPassport** [comment]
Again, not sure if this is the right method to ask questions and happy to remove these issues if that's the case

**Comment by schnuerle** [comment]
It is meant to be just the street name, eg "Center St". But I don't see the harm in using an address if warranted as this field is a bit more for informational purposes. Though I suspect most zones would span more than one address, maybe there are cases for defining the specific address, which could help maybe clarify which side of a street a zone is at?

**Comment by mplsmitch** [comment]
My interpretation of this is that it's only the name of the street, so "N Center St" would be valid, but the example "438 N Center St" would not. If there's a use case requiring the street number it could be redefined, or we could add a `street_number` field. GBFS has a `stations[].address` field which [combines the two](https://github.com/MobilityData/gbfs/blob/master/gbfs.md#station_informationjson).

**Comment by schnuerle** [comment]
Could someone make a PR for this please?

**Comment by schnuerle** [comment]
@mplsmitch can you make a PR for this please?

**Comment by schnuerle** [comment]
Does the language change here address your concerns @MirandaBradshawPassport ? From @mplsmitch #139 pull request.

> The name of the street that this Curb Zone is on, including directionals. SHOULD NOT contain address numbers. Example: `Main Street NE`

**Comment by schnuerle** [comment]
Fixed with #139
