### ISSUE TITLE
Create Example Clarity Around User Classes versus Vehicle Types for Disabled Placard Requirements

### ISSUE THREAD

**Issue by mschwartzie** [openmobilityfoundation/curb-data-specification#142]
### Is your feature request related to a problem? Please describe.

Under User Classes (https://github.com/openmobilityfoundation/curb-data-specification/tree/main/curbs#user-classes), the example given describes a much less common implementation around a vehicle type requirement that the vehicle type is `handicap-accessible` rather than the use case where a person requires a disabled parking placard.  

### Describe the solution you'd like

Recommend describing the much more common implementation where you describe Purpose as `disabled-parking-permit`

### Is this a breaking change

 * No, not breaking

### Impacted Spec

For which spec is this feature being requested?

 * `Curbs`

**Comment by schnuerle** [comment]
Thanks @mschwartzie what SMART city or cities are you submitting this for?

**Comment by mschwartzie** [comment]
@schnuerle SFMTA

**Comment by schnuerle** [comment]
Could be part of the work on #143 if we can get a PR for both issues for the patch release.

**Comment by mplsmitch** [comment]
Here's how the EU is proposing to handle this: [https://ec.europa.eu/social/main.jsp?catId=1139](https://ec.europa.eu/social/main.jsp?catId=1139)

**Comment by schnuerle** [comment]
@mplsmitch can you make a new PR for this that includes the new well known value of `disabled-parking-permit`? And include what is recommended in #143 in the same PR.

**Comment by schnuerle** [comment]
Closed with #160 for the 1.0.1 patch.
