### ISSUE TITLE
Do a 1.0.1 bug fix release to fix event API examples?

### ISSUE THREAD

**Issue by jiffyclub** [openmobilityfoundation/curb-data-specification#156]
Would it be possible to do a bug fix release in the near future? The curb event examples have the wrong response structure in the main branch and 1.0.0 release. They have been corrected in the dev branch via https://github.com/openmobilityfoundation/curb-data-specification/commit/05d3e37ad46de568b2eac66c4e56c1eaf45cc060 several months ago, but implementers of an events API are unlikely to find their way to those examples.

Correct examples in the dev branch: https://github.com/openmobilityfoundation/curb-data-specification/blob/61c87a6468016b143600f0b1b672f507d1939c90/events/examples.md

Incorrect examples:
- 1.0.0 release: https://github.com/openmobilityfoundation/curb-data-specification/blob/1.0.0/events/examples.md
- main branch: https://github.com/openmobilityfoundation/curb-data-specification/blob/d0de87b1bd6c1848f6d5ca06a8686c116764141f/events/examples.md

**Comment by schnuerle** [comment]
Yes if you can do a quick PR, I can work it into the 1.0.1 patch which I want to finish this week!

**Comment by jiffyclub** [comment]
This is already fixed in the dev branch, it only needs to get it into an official release.

**Comment by schnuerle** [comment]
Yes we will be doing this very soon!
