### ISSUE TITLE
Curb Policy

### ISSUE THREAD

**Issue by bhamlinSDOT** [openmobilityfoundation/curb-data-specification#56]
"[**Policy**](https://github.com/openmobilityfoundation/curb-data-specification/blob/main/curbs/README.md#policy)
A Policy object is a rule that allows or prohibits a particular set of users from using a particular curb at a particular time or times. **_Multiple Policy objects together define the full extent of regulations within a Curb Zone._** Much of this is similar to curbLR."

My understanding is that Curb Zones _always have a common regulation_. Isn't each Policy object a separate regulation which would make multiple policy objects within a Curb Zone impossible?

**Comment by schnuerle** [comment]
Maybe the confusion here come from the way this is worded? My reading of "Multiple Policy objects" means using multiple CDS Curbs Policy data objects which are layered into a Curb Zone.  For example, a Curb Zone could have 1 object which says there is a 60 minute parking limit for anyone, and object 2 that says commercial vehicles are only allowed from 8am - 5pm. 

Each 'object' is like a curb street sign with a specific policy rule affecting a curb.

You can see one policy JSON object in [this example](https://github.com/openmobilityfoundation/curb-data-specification/blob/feature-release-work-1/curbs/examples.md#curb-zones-minimum) - 60 minute limit.

Does that make sense to you? If so we should come up with some wording to make that clearer here and in other parts of the spec.

**Comment by schnuerle** [comment]
Based on the steering committee review of this, what do you all think are the next steps @bhamlinSDOT @zanebclark ?

**Comment by zanebclark** [comment]
I think I'm satisfied, @schnuerle
