### ISSUE TITLE
OpenAPI Definition

### ISSUE THREAD

**Issue by jamesdwilson** [openmobilityfoundation/curb-data-specification#87]
In the interest of rapid development, what are your thoughts on providing an OpenAPI/swagger definition file?

This can be used to generate API endpoint source code as well as check validity of endpoints.

**Comment by jamesdwilson** [comment]
@schnuerle Hi is there any update on this or do you know of ANY strict computer-parsable technical specification format we can make use of to help us rapidly develop our API? As far as I can tell it is only available in loose wiki/markdown style text documents.

Thank you

**Comment by schnuerle** [comment]
Hi @jamesdwilson. Right now we don't have a schema for CDS 1.0, or something similar like Swagger. It may come in the next release, if we can find a community member or members to lead the effort and do the work, maybe with the Working Group Steering Committee. 

We could also look at funding this work if there is a demand, so I appreciate your efforts in pushing for this. I hope others will chime in too to help get it prioritized. As more orgs start using it after this first release, I imagine there will be a push for it.

For MDS, we do have a [schema](https://github.com/openmobilityfoundation/mobility-data-specification/tree/main/schema) which you can see an example of [here](https://github.com/openmobilityfoundation/mobility-data-specification/blob/main/provider/status_changes.json), and there has been a call for a [swagger definition or OpenAPI defintion there too](https://github.com/openmobilityfoundation/mobility-data-specification/issues/281).

**Comment by schnuerle** [comment]
If time allows, we will bring this up for discussion at the MDS [public Working Group meeting](https://github.com/openmobilityfoundation/mobility-data-specification/wiki/Web-conference-notes,-2022.04.14-(MDS-Working-Group)) tomorrow, so please comment here or attend and bring your thoughts. 

It will be MDS focused (not CDS) but the need for this in both MDS and CDS could help make it happen, the volunteer base would be larger to help with the work, and the solution will be the same for both specs to make them consistent within the OMF.

The Curb Work Group Steering Committee had multiple members that were both interested in this idea, and willing to spend some time and share their expertise on it.

**Comment by jamesdwilson** [comment]
Not my call I know but Stoplight looks like a good option to me, assuming there is always the option to export all data.

RE: MDS working group meeting, I like this a lot, but wondering what and when the impact will be on CDS as there is intentionally no overlap on CDS for 1.0 as far as I understand. Isn't MDS planned for a potential future version of CDS?

Thank you

**Comment by schnuerle** [comment]
Yes there is no current overlap in the spec between CDS and MDS yet, and that was intentionally for the first release. But I expect there to be connections (like referencing MDS trip IDs or CDS curb zone IDs, etc) between them in the next releases (MDS 2.0 and CDS 1.1 or 2.0). 

We have open Issues to discuss there now.

https://github.com/openmobilityfoundation/curb-data-specification/issues/17
https://github.com/openmobilityfoundation/mobility-data-specification/issues/731

For OpenAPI or equivalent, what I meant was the solution we pick should be the same and work for both specs, to reduce the overhead and remain consistent with the OMF organization.

**Comment by schnuerle** [comment]
This topic will be the entire focus of our next [public working group meeting tomorrow](https://github.com/openmobilityfoundation/curb-data-specification/wiki/Web-Conference-2022.05.17-Curb#agenda). Please come if you can @jamesdwilson.

**Comment by schnuerle** [comment]
There is now a feature branch in this repo called [`feature-openapi`](https://github.com/openmobilityfoundation/curb-data-specification/tree/feature-openapi) where will be started by the WGSC which will lead to a pull request, and the WG can contribute with comments, their own pull requests, etc.

**Comment by schnuerle** [comment]
I created Pull Request #100 for this, which can allow for line-item comments.

**Comment by BigIdeas** [comment]
> Did you write all of it by hand or use a tool? Have you tried it in any editor/viewer tools?

I used Stoplight's editor to get it started and then filled the rest in by hand. I've only viewed it in Stoplight (mainly to check for syntax errors).

It's using version 3.1.0 of the OpenAPI spec (the current version), and it looks like Swagger's tools only support up to version 3.0.3 which is why I've only checked it in Stoplight. I think it would be pretty trivial to downgrade the spec to 3.0.3 if we want to for compatibility though.

**Comment by schnuerle** [comment]
Here it is for others to view in Stoplight's online viewer, in an OMF branded account:

https://openmobilityfnd.stoplight.io/docs/curb-data-specification/4wvvx7c8j5ymv-cds-curbs

**Comment by schnuerle** [comment]
Instead of putting the OpenAPI YAML in the CDS repo, I created a new repo where this schema code could live. Just a draft and the WGSC will be discussing this in more detail soon.

https://github.com/openmobilityfoundation/cds-openapi/blob/main/README.md

Updated Stoplight draft with placeholder for all APIs:

https://openmobilityfnd.stoplight.io/docs/curb-data-specification/branches/main

Added some examples to our working doc of what other orgs are doing in this space (feel free to add more examples):

https://openmobilityfnd.stoplight.io/docs/curb-data-specification/branches/main

**Comment by schnuerle** [comment]
Here's where current work is being done by @michael-danko-passport:
 
https://github.com/openmobilityfoundation/cds-openapi/tree/v1.0.0-dev

**Comment by schnuerle** [comment]
FYI we have the complete MDS 2.0 OpenAPI definition and Stoplight page up and running now!

https://openmobilityfnd.stoplight.io/docs/mds-openapi/

**Comment by schnuerle** [comment]
@michael-danko-passport I did update the home page as part of our MDS 2.0 OpenAPI work.  You can see it [here](https://openmobilityfnd.stoplight.io/).

Now that we have that up and running, it would be great to 1) finish the work on OpenAPI for CDS and 2) structure it to match how it was done in MDS. 

**For MDS,** we have each API defined as such, with each endpoint under it, and then schema definitions below that:

<img width="275" alt="image" border="1" src="https://github.com/openmobilityfoundation/curb-data-specification/assets/1285077/8c900028-d8a7-48de-8391-a2fe1ca50046">


**With CDS,** we have it arranged a bit differently now, with all APIs under one level and schemas under that too: 

<img width="276" alt="image" src="https://github.com/openmobilityfoundation/curb-data-specification/assets/1285077/6c5ec0c4-59b9-4478-9a49-59d70496cfa1">


What do you and @BigIdeas think it would take to finish and align the schemas and endpoints like in MDS?

**Comment by jamesdwilson** [comment]
Hi @schnuerle - respectfully and just FYI, I have moved on from this project. Take care!

**Comment by schnuerle** [comment]
We will be talking about this at next week's [Working Group meeting](https://github.com/openmobilityfoundation/curb-data-specification/wiki/Web-Conference-2023.06.27-Curb#agenda) for inclusion in a forthcoming CDS 1.0.1 patch release, so please attend if you can.

**Comment by schnuerle** [comment]
Merged with #100 PR
